language: python
python:
  - 3.5
  - 3.5-dev
  - 3.6
  - 3.6-dev
  - nightly
install:
  - pip install -U pip
  - GITHUB_PROTOCOL=https make install
  - pip install coveralls
script:
  - make test
after_success:
  - coveralls
