language: python
python:
  - 3.5
  - 3.5-dev
  - 3.6
  - 3.6-dev
  - nightly
install:
  - SKIP_VIRTUALENV=1 GITHUB_PROTOCOL=https make install
  - env
  - pip install coveralls
script:
  - SKIP_VIRTUALENV=1 GITHUB_PROTOCOL=https make test
after_success:
  - coveralls
