repositories:
    - bonobo[dev]:
        origin: git@github.com:{{ github_username }}/bonobo.git
        upstream: git@github.com:python-bonobo/bonobo.git

    - bonobo-docker[dev]:
        origin: git@github.com:{{ github_username }}/bonobo-docker.git
        upstream: git@github.com:python-bonobo/bonobo-docker.git

    - bonobo-sqlalchemy[dev]:
        origin: git@github.com:{{ github_username }}/bonobo-sqlalchemy.git
        upstream: git@github.com:python-bonobo/bonobo-sqlalchemy.git

    - bonobo-selenium[dev]:
        origin: git@github.com:{{ github_username }}/bonobo-selenium.git
        upstream: git@github.com:python-bonobo/bonobo-selenium.git

    - vendors/edgy-event:
        origin: git@github.com:python-edgy/event.git

    - vendors/edgy-project:
        origin: git@github.com:python-edgy/project.git
