repositories:
    - 'bonobo@develop[dev,jupyter]':
        origin: {{ github('bonobo') }}
        upstream: {{ github('bonobo', user='python-bonobo') }}

    - 'bonobo-docker[dev]':
        origin: {{ github('bonobo-docker') }}
        upstream: {{ github('bonobo-docker', user='python-bonobo') }}

    - 'bonobo-sqlalchemy[dev]':
        origin: {{ github('bonobo-sqlalchemy') }}
        upstream: {{ github('bonobo-sqlalchemy', user='python-bonobo') }}

    - 'bonobo-selenium[dev]':
        origin: {{ github('bonobo-selenium') }}
        upstream: {{ github('bonobo-selenium', user='python-bonobo') }}

    - 'cookiecutter-bonobo':
        upstream: {{ github('cookiecutter-bonobo', user='python-bonobo') }}

    - 'vendors/whistle':
        origin: {{ github('whistle', user='python-whistle') }}

    - 'vendors/medikit':
        origin: {{ github('medikit', user='python-medikit') }}

